comment: false

language: R

sudo: false

cache: packages

r_packages:
  - covr

codecov:
  token: 7bb78e01-105a-43e2-af8c-1cb6eb16d21c

after_success:

- Rscript -e 'covr::codecov()'

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
